/**
 * O*NET occupation and skill dataset for the SkillSprout career trajectory engine.
 *
 * This module loads the full O*NET 28.3 database (1,016 occupations) from a
 * pre-processed JSON file generated by `scripts/process-onet.mjs`.
 *
 * Each occupation includes up to 15 top skills (merged from O*NET Skills +
 * Knowledge domains) ranked by importance rating (1–5 scale).
 *
 * Data source: O*NET Database 28.3
 *   https://www.onetcenter.org/database.html
 *   License: CC BY 4.0
 *
 * Transition framework references:
 *   Anthropic (2025). "The Macroeconomic Impact of Artificial Intelligence"
 *   — uses O*NET task and skill data to model AI-driven labor transitions
 */

import onetData from "./onet-full.json";

// ── Types ──────────────────────────────────────────────────────────

export interface OnetSkill {
  name: string;        // O*NET canonical skill/knowledge name
  importance: number;  // Importance rating (1.0–5.0)
}

export interface OnetOccupation {
  code: string;        // O*NET-SOC code (e.g., "15-1252.00")
  title: string;       // Standard Occupational Title
  zone: number;        // Job Zone 1-5 (education/training proxy)
  category: string;    // SOC major group label
  skills: OnetSkill[]; // Top 15 skills by importance
}

// ── Data ───────────────────────────────────────────────────────────

const typedData = onetData as {
  version: string;
  generated: string;
  source: string;
  license: string;
  stats: { occupations: number; uniqueSkills: number; categories: number };
  occupations: OnetOccupation[];
};

export const occupations: OnetOccupation[] = typedData.occupations;

export const dataInfo = {
  version: typedData.version,
  source: typedData.source,
  license: typedData.license,
  stats: typedData.stats,
};

// ── Derived catalogs ───────────────────────────────────────────────

/** All unique skill names across the dataset. */
export const SKILL_CATALOG: string[] = (() => {
  const set = new Set<string>();
  for (const occ of occupations) {
    for (const s of occ.skills) {
      set.add(s.name);
    }
  }
  return [...set].sort();
})();

/** All unique occupational categories. */
export const CATEGORIES: string[] = (() => {
  const set = new Set<string>();
  for (const occ of occupations) set.add(occ.category);
  return [...set].sort();
})();
